# -*- coding: utf-8 -*-
"""DSC-522-AI_Assignment06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dqfkWgngH-zB6gZcSjsTdp2CNCCEy518
"""

# mount the google drive 
from google.colab import drive
drive.mount("/content/drive")

# Downloaded 
# Importing data from google drive
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/seattle-weather.csv")

# Take backup data
data_orig = data.copy()

data.head()

data[['Year', 'Month', 'Day']] = data['date'].str.split('-', expand=True)

data.head()

data_modified = data.drop(columns=['date'])

data_modified.head()

labels = data_modified['weather']
features = data_modified.drop(columns=['weather'],axis=1)

labels.shape

features.shape

#sklearn library to split the test and train data.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0, max_depth=5 )
clf.fit(X_train, y_train)
predicted_labels = clf.predict(X_test)

#Calculating accuracy values.
from sklearn.metrics import accuracy_score
accuracy_score(predicted_labels, y_test)

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0, max_depth=5 )
clf.fit(X_train, y_train)
predicted_labels = clf.predict(X_test)

from sklearn import tree
from matplotlib import pyplot as plt
fig = plt.figure(figsize=(30,20))
_ = tree.plot_tree(clf, 
                   feature_names=data_modified.columns,  
                   class_names=pd. unique(data['weather']),
                   filled=True)